name: Publish crate

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install cargo-v
        run: cargo install cargo-v
      - name: bump semver
        run: cargo v -y
      - name: push new version tag to repo
        run: git push origin master --tags
      - name: publish crate
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
